# Generated by Django 3.2.9 on 2022-01-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userproflie_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproflie',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activity', to='api.activity'),
        ),
    ]
